# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ead34ea3b20686654fdd80933ba3c330aaa9e3fa003c5844c95464df586fb2c42192efe4400e83cfb0301d202238eb248070e8dfd4a39ccffc52a75c43bb5c2

test:
  secret_key_base: 703d6b9c6ca3216d0cacb913f11bc7af678b3c6e27e460adac287229617e902d8801a42caa8b639114599779d9a6ec443f2926c08c1fb50417b08fccd5839b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
